<?php
$posts = $block->getPosts();
?>

<h2>Category Posts</h2>

<?php if (count($posts)) : ?>

    <div class="category-posts">

        <?php foreach ($posts as $post) : ?>

            <div class="post-item">

                <?php if ($post->getThumbnail()) : ?>

                    <img
                        src="<?= $block->getMediaUrl() . $post->getThumbnail(); ?>"
                        width="200"
                    />

                <?php endif; ?>

                <h3>
                    <?= $escaper->escapeHtml($post->getTitle()) ?>
                </h3>

                <p>
                    <?= $post->getShortDescription() ?>
                </p>

            </div>

        <?php endforeach; ?>

    </div>

<?php else : ?>

    <h3>No Posts Found</h3>

<?php endif; ?>